version: '2.4'
services:
  server:
    image: joshperry/govpn
    build: .
    expose:
      - 443
      - 9000
      - 6060
    ports:
      - "443:443"
      - "9000:9000"
      - "6060:6060"
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    command: [ '/server' ]

  client:
    image: joshperry/govpn
    scale: 3
    build: .
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    command: [ '/client' ]
    links:
      - server
